services:
  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache
    ports:
      - "${GANACHE_PORT}:${GANACHE_PORT}"
    environment:
      - MNEMONIC=${MNEMONIC}
    command: >
      --host 0.0.0.0
      --port ${GANACHE_PORT}
      --mnemonic "${MNEMONIC}"
      --networkId 1337
      --chainId 1337
      --defaultBalanceEther 1000
      --accounts 10
      --gasLimit 12000000

  hardhat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hardhat
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - ganache
    environment:
      - MNEMONIC=${MNEMONIC}
      - HARDHAT_PORT=${HARDHAT_PORT}
      - GANACHE_HOST=ganache
      - GANACHE_PORT=${GANACHE_PORT}
    ports:
      - "${HARDHAT_PORT}:8545"
    command: npx hardhat node

volumes:
  node_modules: